### ISSUE TITLE
Updated pdftk version?

### ISSUE THREAD

**Issue by StevenHarlow** [millie/heroku-buildpack-ruby-pdftk#4]
Hi Millie, Do you have the updated pdftk versions?  There are a number of bug fixes for certain pdfs, as well as the ability to use multi-letter handles for referencing in the versions since these binaries.  I'm running into issues where pdftk works on my dev machine but not in heroku, due to the differences in versions.  I can go through the legwork of installing the binaries myself, but wanted to check if you had them already (or if not, and I do the legwork, if you'd like a pull request)

Steve

**Comment by millie** [comment]
Hey @StevenHarlow - I stopped actively working on this project a while ago, but happy to take a pull request if you're working on it

**Comment by StevenHarlow** [comment]
Do you think you could provide me with some pointers/references about how
you got your bin and lib files that are in that tarball?  I figured it'd be
the same process as I've done before on heroku with installing custom
binaries, but it doesn't seem to work.
